INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Acre',  'AC', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Alagoas',  'AL', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Amapá',  'AP', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Amazonas',  'AM', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Bahia',  'BA', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Ceará',  'CE', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Distrito Federal',  'DF', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Espírito Santo',  'ES', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Goiás',  'GO', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Maranhão',  'MA', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Mato Grosso',  'MT', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Mato Grosso do Sul',  'MS', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Minas Gerais',  'MG', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Pará',  'PA', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Paraíba',  'PB', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Paraná',  'PR', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Pernambuco',  'PE', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Piauí',  'PI', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Rio de Janeiro',  'RJ', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Rio Grande do Norte',  'RN', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Rio Grande do Sul',  'RS', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Rondônia',  'RO', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Roraima',  'RR', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Santa Catarina',  'SC', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'São Paulo',  'SP', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Sergipe',  'SE', 1, 1, 1);
INSERT INTO estado (esta_nome, esta_sigla, esta_status, esta_fk_user_pk_id, esta_fk_pais_pk_id) VALUES (  'Tocantins',  'TO', 1, 1, 1);
